export const SITES = [
  { id: 'landing', name: 'South Landing', x: 0, z: 270, kind: 'landing' },
  { id: 'lodge', name: 'The Keeper’s Lodge', x: -90, z: 185, kind: 'building', model: 'lodge.glb', room: 'lodge', scale: [18, 16] },
  { id: 'prison', name: 'Greywake Detention Annex', x: -58, z: 105, kind: 'facility' },
  { id: 'archive', name: 'Survey Archive', x: -170, z: 60, kind: 'building', model: 'archive.glb', room: 'archive', scale: [17, 14] },
  { id: 'headland', name: 'West Headland', x: -210, z: -120, kind: 'vantage' },
  { id: 'headland_stake', name: 'West Survey Stake', x: -186, z: -120, kind: 'vantage' },
  { id: 'tower', name: 'Signal Tower', x: 59, z: -228, kind: 'building', model: 'signal_tower.glb', room: 'tower', scale: [14, 14] },
  { id: 'east_ridge', name: 'East Survey Ridge', x: 232, z: -120, kind: 'vantage' },
  { id: 'north_jetty', name: 'North Inlet Jetty', x: -65, z: -315, kind: 'landing' },
  { id: 'radio', name: 'Radio House', x: 150, z: -55, kind: 'building', model: 'radio_house.glb', room: 'radio', scale: [17, 13] },
  { id: 'pump', name: 'Pump House', x: 125, z: 130, kind: 'building', model: 'pump_house.glb', room: 'pump', scale: [17, 13] },
  { id: 'tunnel', name: 'Service Tunnel', x: 167, z: 150, kind: 'hatch' },
];

// World coordinates, in metres. The west and east survey stakes lie on the
// inland extensions of the true and false leading-light lines respectively.
export const NAV_LIGHTS = {
  front: { x: -100, z: -286, height: 47 },
  main: { x: -160, z: -171, height: 27 },
  standby: { x: 50, z: -211, height: 21 },
};

export const ROOMS = {
  lodge: { title: 'Keeper’s Lodge', width: 16, depth: 12, tint: 0x514638, floor: 0x403a30 },
  archive: { title: 'Survey Archive', width: 16, depth: 12, tint: 0x45494a, floor: 0x353b3d },
  tower: { title: 'Signal Tower', width: 13, depth: 12, tint: 0x4a4a43, floor: 0x393a36 },
  radio: { title: 'Radio House', width: 16, depth: 12, tint: 0x3d494b, floor: 0x303b3e },
  pump: { title: 'Pump House', width: 16, depth: 12, tint: 0x49463e, floor: 0x35342f },
};

export const CHAPTERS = [
  {
    title: 'ARRIVAL',
    weather: 'mist',
    objective: 'Find Iris Hale’s message inside the keeper’s lodge.',
    required: ['iris_note', 'window_reflection', 'lodge_working_carbon'],
    radio: 'Greywake shore control to Mara Vale. The lodge has power. Stay inside until the squall passes.',
  },
  {
    title: 'THE REPORT',
    weather: 'rain',
    objective: 'Reconstruct Mara’s signing decision, then compare the archive’s original and later records.',
    required: ['official_log', 'captain_statement', 'archive_signing_finding', 'archive_reconstruction'],
    radio: 'That inquiry was settled years ago, Mara. Paper left in salt air can say anything.',
  },
  {
    title: 'THREE LIGHTS',
    weather: 'rain',
    objective: 'Compare both survey sightlines, then inspect the tower controls.',
    required: ['headland_view', 'east_ridge_view', 'tower_panel', 'alignment_solution'],
    radio: 'The western headland is unsafe. You have enough to write your report without going there.',
  },
  {
    title: 'THE VOICE',
    weather: 'storm',
    objective: 'Trace the radio voice, find Iris’s physical evidence, and locate her.',
    required: ['radio_patch', 'radio_route_verified', 'lamp_strip', 'tunnel_signal'],
    radio: 'You are letting one missing technician turn an old accident into a conspiracy.',
  },
  {
    title: 'THE SAFE LINE',
    weather: 'storm',
    objective: 'Restore the pump, guide the launch into the north inlet, and open the service tunnel.',
    required: ['pump_power', 'launch_guided', 'iris_rescued'],
    radio: 'Rescue launch offshore. We see two sets of lights. Greywake, confirm the safe approach.',
  },
  {
    title: 'DAYBREAK',
    weather: 'dawn',
    objective: 'Reconnect the mainland line and file a correction limited to what the evidence proves.',
    required: ['iris_handoff', 'daybreak_report'],
    radio: 'Iris here. I have copies of the originals. This time, put each uncertainty in the report before anyone signs it.',
  },
];

// Coordinates for indoor clues are local to each room's center, in meters.
export const CLUES = [
  {
    id: 'iris_note', room: 'lodge', x: -3.4, z: -2.5, minChapter: 0,
    name: 'Iris’s letter', category: 'DOCUMENT',
    body: '<p><strong>Mara,</strong> the old report says the standby rear lamp was disabled. It was not. I found the lamp-command strip, and it does not match the typed log.</p><p>You signed the conclusion. I need you to see the alignment yourself. I will be at the radio house after dusk.</p><p>— Iris Hale</p>',
    journal: 'Iris says a physical lamp-command strip contradicts the log I signed seventeen years ago.',
    radio: 'A letter is not evidence. Iris has been working alone for weeks.',
  },
  {
    id: 'window_reflection', room: 'lodge', x: 5.2, z: -3.2, minChapter: 0,
    name: 'Rain-covered window', category: 'OBSERVATION',
    body: '<p>Through the wet glass, a third pale light hangs beside the harbor pair. You clear the condensation with your sleeve. It vanishes.</p><p>The apparent light was the reflection of a lamp behind you. The glass changed what you thought you saw.</p><p>But the captain saw his light from the water, not from this room.</p>',
    journal: 'The lodge window created a false third light by reflection. It does not explain the captain’s sighting at sea.',
    radio: 'There. A reflection. That is all the third light ever was.',
  },
  {
    id: 'lodge_working_carbon', room: 'lodge', x: -2.2, z: 2.65,
    minChapter: 0, special: 'lodge',
    name: 'Working carbon comparison', category: 'CASE COMPARISON',
    body: '<p>Mara’s working carbon reads <em>lamp status unresolved; obtain relay original</em>. That qualification was struck out before she signed the summary. The paper establishes what she removed from her finding, while the old lamp circuit still needs independent proof.</p>',
    journal: 'My working carbon warned that lamp status was unresolved. I removed that qualification before signing. These papers do not prove which rear lamps operated.',
  },
  {
    id: 'lodge_photo', room: 'lodge', x: 0.4, z: 2.2, minChapter: 0, optional: true,
    name: 'Old crew photograph', category: 'PHOTOGRAPH',
    body: '<p>The keeper, Elias Ward, stands beside the old tower crew. Someone has scratched his face from the print, but left his name written on the back.</p><p>The photograph was taken the week of the wreck.</p>',
    journal: 'Elias Ward operated the island lights during the wreck. His face has been scratched from a crew photograph.',
  },
  {
    id: 'official_log', room: 'archive', x: -4.1, z: -0.1, minChapter: 1,
    name: 'Official accident log', category: 'DOCUMENT',
    body: '<p><strong>21:14 — Main rear lamp active. Standby lamp disabled.</strong></p><p>The official digital export repeats that line at the moment the vessel entered the channel. The original paper column is missing from this binder.</p><p>Your seventeen-year-old signature is at the bottom: <strong>Mara Vale, junior analyst.</strong></p>',
    journal: 'The typed log says only the main rear lamp operated. The original paper record is absent; my signature approved the conclusion.',
    radio: 'You checked the log then. You were thorough. Do not rewrite your own memory because you feel guilty.',
  },
  {
    id: 'captain_statement', room: 'archive', x: 4.2, z: -0.1, minChapter: 1,
    name: 'Captain’s testimony', category: 'TESTIMONY',
    body: '<p>“The lower light held steady. I brought it into line with the upper light. Then there was another upper light, farther east. I saw the pair I had trained for. I did not turn toward the reef.”</p><p>A handwritten note in the margin reads: <strong>Uncorroborated. Possible stress confusion.</strong> The handwriting is yours.</p>',
    journal: 'The captain described a third light and a false alignment. I marked the testimony uncorroborated.',
    radio: 'People remember lights that were never there. You knew that when you wrote the margin note.',
  },
  {
    id: 'archive_chart', room: 'archive', x: 0.1, z: 2.1, minChapter: 1,
    name: 'Harbor survey chart', category: 'CHART',
    body: '<p>Two aligned lights mark the safe north inlet. A reef cuts across the western approach. A pencil mark shows the planned position of a <strong>standby rear lamp</strong> east of the working tower.</p><p>The plan was never crossed out. Its false line crosses the true line at the front lamp, then runs west toward the reef.</p>',
    journal: 'The island chart shows the standby lamp east of the main rear light. Its seaward line crosses west of the front lamp, toward the reef.',
  },
  {
    id: 'archive_signing_finding', room: 'archive', x: 0, z: 0.05, minChapter: 1, special: 'signing',
    name: 'Signing-room reconstruction', category: 'DOCUMENTED DECISION',
    body: '<p>Mara had the typed lamp-status export and the captain’s conflicting account. Her draft asked for the missing relay original. The office closure docket set a deadline but allowed unresolved sources to remain qualified.</p><p>She accepted the typed export as primary, struck out <em>lamp status unresolved; obtain relay original</em>, and marked the captain’s account possible stress confusion. That was her documented choice. These papers do not prove which rear lamp circuits operated.</p>',
    journal: 'At signing, I knew the captain’s account conflicted with the typed export and the relay original was missing. Under a deadline I removed my unresolved-status warning and discounted his testimony. The circuit state was still unproved.',
  },
  {
    id: 'archive_reconstruction', room: 'archive', x: 0, z: 1.0, minChapter: 1, special: 'archive',
    name: 'Case reconstruction desk', category: 'ARCHIVE COMPARISON',
    body: '<p>After reconstructing Mara’s signing decision, arrange the records by source and date. Decide which parts of the old finding can still be defended. The physical relay record is absent from this room.</p>',
    journal: 'The old finding removed a known uncertainty. The archive warrants reopening the inquiry, but cannot yet prove which rear lamps operated.',
  },
  {
    id: 'headland_view', world: [-186, -120], nearSite: 'headland_stake', minChapter: 2, special: 'survey',
    name: 'West survey stake', category: 'FIELD PHOTOGRAPH',
    body: '<p>Through the survey camera, the lower front lamp and <strong>western main rear lamp</strong> share a bearing, one above the other. Project that line seaward: it marks the deep channel into the north inlet.</p><p>Record the bearing before the rain closes in.</p>',
    journal: 'From the west survey stake, the front and main rear lamps align along the deep north-inlet channel.',
    radio: 'Mara, leave the cliff. The weather is closing in.',
  },
  {
    id: 'east_ridge_view', world: [232, -120], minChapter: 2, special: 'survey',
    name: 'East survey stake', category: 'FIELD PHOTOGRAPH',
    body: '<p>Here, the lower front lamp and <strong>eastern standby rear lamp</strong> share a bearing. Extend that line seaward and it crosses toward the western reef.</p><p>The island had two convincing light pairs. Only one led through deep water.</p>',
    journal: 'From the east survey stake, the front and standby rear lamps align along a line that reaches the western reef.',
    radio: 'That lamp was never supposed to be powered. What are you looking at?',
  },
  {
    id: 'tower_panel', room: 'tower', x: -3, z: -1.8, minChapter: 2,
    name: 'Tower control panel', category: 'MACHINERY',
    body: '<p>The standby rear lamp is still connected to an old emergency circuit. Modern control software suppresses it; a manual failover can energize it again.</p><p>Someone has recently tested the switch. The cover is warm.</p>',
    journal: 'A standby rear lamp still exists. A failover circuit can bring it on despite the newer software.',
    radio: 'Please do not touch the lighting circuit. It guides boats in from the sea.',
  },
  {
    id: 'alignment_solution', room: 'tower', x: 3.3, z: 1.8, minChapter: 2, special: 'alignment',
    name: 'Alignment board', category: 'DEDUCTION',
    body: '<p>The front lamp can align with either rear lamp. Compare both field photographs: which pair marks the deep north-inlet channel?</p>',
    journal: 'The western main rear lamp and the lower front light mark the safe channel. The eastern standby rear lamp points over the reef.',
  },
  {
    id: 'radio_patch', room: 'radio', x: -3.5, z: -2, minChapter: 3,
    name: 'Disconnected mainland patch', category: 'MACHINERY',
    body: '<p>The cable that should connect the island repeater to mainland control is unplugged. Yet the voice on the “mainland” channel continues to speak.</p><p>A local microphone lies beside the repeater. Its worn button clicks exactly like the click before every transmission.</p>',
    journal: 'The shore-control voice is transmitting from this island. The mainland connection was deliberately cut.',
    radio: 'You found the patch. I had to keep you calm. I could explain if you would listen.',
  },
  {
    id: 'radio_route_verified', room: 'radio', x: -0.7, z: 2.7, minChapter: 3, special: 'routing',
    name: 'Repeater routing controls', category: 'RADIO CIRCUIT',
    body: '<p>Compare the switchboard, loop transmission ledger, and loose mainland patch. Trace which microphone carried the voice, then reconnect the genuine shore lead and verify who answers.</p>',
    journal: 'The claimed shore-control calls used the island loop. The disconnected mainland patch could not have carried them.',
  },
  {
    id: 'operator_note', room: 'radio', x: 3.5, z: 1.9, minChapter: 3,
    name: 'Operator’s notebook', category: 'DOCUMENT',
    body: '<p>“One line in one log. That was all it took. Once the report said captain error, no one asked me to move the standby lamp.”</p><p>The rest of the page is torn away.</p>',
    journal: 'Elias knew the official finding protected him and left the standby lamp in place.',
  },
  {
    id: 'lamp_strip', room: 'pump', x: 3.3, z: -2.3, minChapter: 3,
    name: 'Mechanical lamp-command strip', category: 'PHYSICAL RECORD',
    body: '<p>In a sealed maintenance tin: a narrow mechanical strip punched by the lamp relay itself. At 21:14, both rear-lamp circuits are marked active.</p><p>Iris has circled the marks. Unlike the typed export, this strip was made by the switch, not by a person entering data.</p>',
    journal: 'The original mechanical strip records both rear lamps active at the time of the wreck. It contradicts the altered typed log.',
    radio: 'I changed one line. I did not put that vessel on the reef.',
  },
  {
    id: 'tunnel_signal', world: [167, 150], minChapter: 3,
    name: 'Voice behind the hatch', category: 'WITNESS',
    body: '<p>Three taps answer your call. Iris is alive beyond the service hatch. Water is at her knees and rising. She heard Elias outside after she found the strip, then heard the outer bolt move. She could not see who moved it; the storm has since jammed the mechanism.</p><p>The pump needs backup power before the gate will open.</p>',
    journal: 'Iris is alive in the flooding service tunnel. She heard Elias at the gate and the bolt move, but did not see who moved it. Backup power must run the pump.',
    radio: 'I did not mean for the gate to jam. I was going to let her out.',
  },
  {
    id: 'pump_power', room: 'pump', x: -3.4, z: -2.2, minChapter: 4, special: 'power',
    name: 'Backup power lever', category: 'MACHINERY',
    body: '<p>Backup power will drain the tunnel and release the gate. The same old bus also feeds the standby rear lamp.</p><p>A rescue launch waits offshore from the north inlet. You can warn it before switching the circuit.</p>',
    journal: 'Backup power is running. The tunnel pump works, but the old standby lamp has lit again.',
  },
  {
    id: 'launch_guided', room: 'pump', x: 3.3, z: 2.1, minChapter: 4, special: 'launch',
    name: 'Harbor radio', category: 'DECISION',
    body: '<p>The rescue launch sees two possible light alignments at the north inlet. Its pilot is holding offshore, waiting for a confirmed bearing.</p>',
    journal: 'I told the rescue launch to hold offshore, then guided it by the western main rear lamp and lower front light.',
  },
  {
    id: 'iris_rescued', world: [167, 150], minChapter: 4, special: 'rescue',
    name: 'Open service hatch', category: 'RESCUE',
    body: '<p>The pump has lowered the water. The gate releases. Iris climbs into the rain carrying the original chart and the technician’s maintenance notes.</p><p>Across the island, the rescue launch’s light moves along the safe line toward the north jetty.</p>',
    journal: 'Iris is safe. The original records and independent sightlines expose the falsified report.',
  },
  {
    // The custody conversation begins at Iris herself. Keeping the required
    // marker on her position prevents the generic chat prompt from hiding the
    // Chapter 6 objective in the tall meadow grass.
    id: 'iris_handoff', world: [176, 157], nearSite: 'tunnel', minChapter: 5, special: 'iris',
    name: 'Iris and the sealed records', category: 'WITNESS AND CUSTODY',
    body: '<p>Iris keeps the original relay strip and chart in her waterproof case. Ask how she wants the originals and the authenticated copies handled. Her testimony belongs to her; Mara cannot decide custody for her.</p>',
    journal: 'Iris chose how her original records and authenticated copies would reach the inquiry and the captain’s family.',
  },
  {
    id: 'daybreak_report', room: 'radio', x: 0, z: 0, minChapter: 5, special: 'daybreak',
    name: 'Mainland correction terminal', category: 'FINAL FINDING',
    body: '<p>Iris has the original records. Reconnect the mainland patch and submit a corrected finding. Every sentence must say what its sources prove and where the evidence ends.</p>',
    journal: 'I signed and transmitted a corrected finding about the relay record, my professional error, Elias’s documented actions, and the limits of what can be proved about intent.',
  },
  // Additional evidence sits at existing buildings, stakes, boardwalks and
  // jetties. Archive and daybreak comparisons make several records essential.
  {
    id: 'arrival_registry', world: [3, 278], nearSite: 'landing', minChapter: 0, optional: true,
    name: 'Landing duty board', category: 'ARRIVAL RECORD',
    purpose: 'Establish that Iris requested Mara specifically and was still acting deliberately when she disappeared.',
    body: '<p>A wet duty card is clipped to the landing rail. <strong>I. Hale requested an independent survey analyst. M. Vale arriving by ferry.</strong> Beneath it, in Iris’s block capitals: <em>Compare both land stations. Extend each bearing out to the water.</em></p>',
    journal: 'Iris arranged my arrival and wanted the light alignments checked against the approach from sea.',
    radio: 'The technician left too many notes. Come inside before you lose the path.',
  },
  {
    id: 'lodge_supply_chit', room: 'lodge', x: 5.5, z: 2.4, minChapter: 0, optional: true,
    name: 'Fresh supply chit', category: 'DOCUMENT',
    purpose: 'Place Elias on the island now while the caller still claims to be mainland shore control.',
    body: '<p>Tea, lamp oil, and radio batteries were signed out yesterday to <strong>E. Ward, keeper</strong>. A second cup is still warm beside the ledger. Someone is living here, close enough to reach the island radio.</p>',
    journal: 'Elias Ward drew supplies yesterday. The lodge is occupied, and its keeper can reach the radio house.',
    radio: 'The island was never abandoned, Mara. A keeper still has work to do.',
  },
  {
    id: 'lodge_unsent_card', room: 'lodge', x: -5.5, z: 2.4, minChapter: 0, optional: true,
    name: 'Unsent condolence card', category: 'LETTER',
    purpose: 'Show Elias living with guilt before the player can reduce him to a faceless conspirator.',
    body: '<p>Six attempts at the same sentence are crossed out. <em>I should have closed the channel that night.</em> There is no address, only the captain’s surname. The card has spent years beneath a pile of new stationery.</p>',
    journal: 'Elias once tried to write to the captain’s family. His draft says he should have closed the channel.',
    radio: 'Put that back. It was never sent, and it will not make a better apology now.',
  },
  {
    id: 'archive_draft_memo', room: 'archive', x: -1.8, z: -0.1, minChapter: 1,
    name: 'Mara’s draft finding', category: 'DOCUMENT',
    purpose: 'Make Mara’s error a specific professional choice instead of a vague guilty memory.',
    body: '<p>Your first draft says <em>lamp status unresolved; obtain relay original.</em> In the signed version, that line is gone. A note in your handwriting explains why: <em>Typed export accepted as primary. Do not delay closure.</em></p>',
    journal: 'I identified the missing relay original, then accepted the typed export and removed the uncertainty before signing.',
    radio: 'You had a deadline and a certified export. Anyone in that office would have closed the file.',
  },
  {
    id: 'archive_revision_stamp', room: 'archive', x: -5.5, z: 2.3, minChapter: 1,
    name: 'Export revision stamp', category: 'RECORD',
    purpose: 'Tie the typed accident log to a later human revision without making the mechanical strip redundant.',
    body: '<p>On the back of the typed export: <strong>REPRINTED TWO DAYS AFTER INCIDENT — E. WARD OPERATOR ACCOUNT.</strong> The stamp proves who made the later copy, not which line changed. The relay strip could answer that.</p>',
    journal: 'The official export was reprinted through Elias’s account two days after the wreck. The stamp alone does not prove the altered value.',
    radio: 'A reprint is not a forgery. The original machine had been moved by then.',
  },
  {
    id: 'archive_witness_addendum', room: 'archive', x: 5.5, z: 2.4, minChapter: 1,
    name: 'Deckhand’s late addendum', category: 'TESTIMONY',
    purpose: 'Give the captain independent corroboration while preserving why Mara called his testimony uncorroborated at the time.',
    body: '<p>A deckhand wrote a month after the finding: <em>I saw a second high light to starboard of the first. I assumed one belonged to shore.</em> The addendum was filed after the inquiry closed, under a different case number.</p>',
    journal: 'A later deckhand statement independently describes two high lights. It arrived after my finding and was never linked to the case.',
    radio: 'A month later, after the newspapers had printed every detail. You know why that mattered.',
  },
  {
    id: 'prison_intake_ledger', world: [-57, 98], nearSite: 'prison', minChapter: 1, optional: true,
    name: 'Detention intake ledger', category: 'CONTEMPORARY RECORD',
    purpose: 'Give the old compound a grounded connection to the wreck investigation and the captain’s firsthand account.',
    body: '<p>The island’s maritime detention annex held the captain for three nights after the wreck. The old block later closed; a small wing now serves as temporary holding again. At the gatehouse intake desk, an officer recorded his statement before the newspapers arrived: <em>Lower lamp with two possible upper lights. Chose the western pair.</em></p><p>The entry proves what he reported that morning. It cannot by itself prove which lamps were lit at sea. The witness comparison board on the nearby registry plinth has spaces for this entry, the captain’s hearing statement, a later addendum, and Mara’s draft.</p>',
    journal: 'A dated intake entry preserves the captain’s account of two upper lights before press coverage. It corroborates the timing of his testimony, not the circuit state.',
    radio: 'He wrote that before anyone showed him the log. I know. I took the statement to the archive myself.',
  },
  {
    id: 'west_gale_chart', world: [-202, -101], nearSite: 'headland', minChapter: 2, optional: true,
    name: 'West headland weather gauge', category: 'FIELD RECORD',
    purpose: 'Ground the deceptive lights in bad visibility without treating weather as the cause of the wreck.',
    body: '<p>Iris clipped a copy of the wreck-night weather reel under the gauge’s rain hood: a violent crosswind and rain at 21:14. The lamp distances fall inside the recorded visibility. A lookout could see both high lights without seeing the reef between them.</p>',
    journal: 'Weather hid the reef, but the two rear lamps were within visibility. The extra light was physically plausible.',
    radio: 'The wind is rising along that edge. Please get back to the trail.',
  },
  {
    id: 'east_benchmark', world: [219, -105], nearSite: 'east_ridge', minChapter: 2, optional: true,
    name: 'East ridge benchmark', category: 'SURVEY MARK',
    purpose: 'Show that Iris prepared an independent reproducible survey rather than asking Mara to trust her word.',
    body: '<p>Iris painted a small triangle on the fixed survey bolt. Her measurements are scratched beneath it: front light, standby rear, reef bearing. You can stand where she stood and check the geometry yourself.</p>',
    journal: 'Iris measured the eastern false alignment from a permanent survey bolt. Her result can be reproduced.',
    radio: 'She was careful, I will give her that. Careful people still choose what they expect to see.',
  },
  {
    id: 'tower_failover_tag', room: 'tower', x: -3.5, z: 3.5, minChapter: 2, optional: true,
    name: 'Emergency circuit tag', category: 'MACHINERY',
    purpose: 'Foreshadow that restoring the rescue pump will also energize the dangerous standby lamp.',
    body: '<p>A red maintenance tag runs from the old standby-lamp switch to the tunnel pump bus. <strong>SHARED EMERGENCY FEED.</strong> The newer console conceals that connection. The handwritten warning says to inform incoming vessels before using backup power.</p>',
    journal: 'The tunnel pump and standby rear lamp share an emergency feed. Restoring the pump will light the false rear lamp again.',
    radio: 'That circuit is old. Please do not test it while there are boats offshore.',
  },
  {
    id: 'tower_training_card', room: 'tower', x: 3, z: -3.2, minChapter: 2, optional: true,
    name: 'Pilot training card', category: 'CHART',
    purpose: 'Give an optional nontechnical explanation of the safe pair before the alignment deduction.',
    body: '<p>A faded card shows the inlet as a narrow dark tongue between reef shelves. <strong>Front + western main rear: deep water.</strong> Its reverse shows the front and eastern standby rear crossing over the western shelf.</p>',
    journal: 'The training card confirms the western main rear light with the front light marks deep water.',
    radio: 'The card was for clear-weather drills. Use the actual survey stakes before you decide.',
  },
  {
    id: 'north_jetty_sounding', world: [-64, -318], nearSite: 'north_jetty', minChapter: 2, optional: true,
    name: 'North jetty depth board', category: 'FIELD RECORD',
    purpose: 'Connect the abstract safe bearing to a visibly usable rescue landing.',
    body: '<p>White numbers on the jetty-edge depth staff mark the deep channel beside it. West of the channel the rock shelf rises sharply. There is room for one careful launch, provided its pilot keeps the true pair in line.</p>',
    journal: 'The north jetty has a deep approach beside a shallow western shelf. A correctly guided launch can land here.',
    radio: 'That berth has not seen a rescue boat in years. Its depth marks may be old.',
  },
  {
    id: 'radio_switchboard', room: 'radio', x: -5.3, z: 2.6, minChapter: 3,
    name: 'Local switchboard ledger', category: 'TRANSMISSION LOG',
    purpose: 'Corroborate that the reassuring shore-control voice is being routed from the island.',
    body: '<p>The switchboard has two numbered feeds: <strong>ISLAND LOOP</strong> from the local microphone and <strong>MAINLAND TRUNK</strong> from the shore socket. The channel selector is wired through the island loop. To establish when it was used, compare the transmission ledger.</p>',
    journal: 'The switchboard can route a local microphone through the same channel as mainland control. The transmission ledger should show which feed carried the calls.',
    radio: 'Yes. I am in the radio house. I wanted you to hear the facts before you saw me.',
  },
  {
    id: 'island_loop_ledger', room: 'radio', x: 5.25, z: 2.75, minChapter: 3,
    name: 'Island-loop transmission ledger', category: 'TRANSMISSION LOG',
    purpose: 'Give the player an independent timestamp comparison for the supposed shore-control calls.',
    body: '<p>The times of every reassuring “shore control” call match entries in the <strong>ISLAND LOOP</strong> column. The mainland column is blank at those minutes. <strong>E.W.</strong> is pencilled beside the active local microphone.</p>',
    journal: 'The supposed shore-control calls match island-loop timestamps; no mainland transmission is logged at those times.',
  },
  {
    id: 'radio_iris_recording', room: 'radio', x: 0, z: -3.7, minChapter: 3, optional: true,
    name: 'Iris’s recorded checklist', category: 'RECORDING TRANSCRIPT',
    purpose: 'Restore Iris’s voice and show her planned evidence chain and safety preparations.',
    body: '<p>Her recorder lists three tasks in a steady voice: photograph both stakes, copy the relay strip, test the pump without energizing the standby lamp. At the end she adds, <em>If I vanish, keep the copies separate.</em></p>',
    journal: 'Iris planned a repeatable survey, copied the physical evidence, and anticipated the shared pump circuit.',
    radio: 'She was preparing for a fight. I was trying to stop her from making one.',
  },
  {
    id: 'radio_unsent_call', room: 'radio', x: 5.4, z: -3, minChapter: 3, optional: true,
    name: 'Unsent distress form', category: 'DOCUMENT',
    purpose: 'Show Elias had a chance to call for help after confining Iris and chose to protect himself.',
    body: '<p><strong>Technician locked behind service gate. Pump failed. Request launch.</strong> The form is filled in, unsigned, and still under the radio glass. Elias knew the situation was becoming dangerous; he never transmitted it.</p>',
    journal: 'Elias drafted a distress call about Iris and the failed pump, then left it unsent.',
    radio: 'I thought I could open the gate before anyone came. Then the weather took the power.',
  },
  {
    id: 'pump_service_order', room: 'pump', x: 0.1, z: -4, minChapter: 3,
    name: 'Wreck-night service order', category: 'MAINTENANCE RECORD',
    purpose: 'Identify Elias’s manual standby action while leaving the physical relay strip as decisive proof it operated.',
    body: '<p><strong>21:10 — main rear feed unstable. E. Ward authorized manual standby.</strong> The order has no line for a harbor warning. Four minutes later, the relay punched two active rear circuits.</p>',
    journal: 'Elias authorized the standby circuit at 21:10. The service order records no warning to approaching vessels.',
    radio: 'The main feed was failing. I thought a second light was safer than darkness. I was wrong.',
  },
  {
    id: 'pump_iris_route', room: 'pump', x: -5.4, z: 2.7, minChapter: 3, optional: true,
    name: 'Iris’s bypass sketch', category: 'FIELD NOTES',
    purpose: 'Let Iris contribute a practical rescue plan rather than existing only as the person to be saved.',
    body: '<p>Iris traced the backup feed, the flood gate, and the dry shelf inside the tunnel. A pencil arrow reads: <em>Pump first. Keep launch offshore until false lamp identified. Gate second.</em></p>',
    journal: 'Iris mapped the rescue sequence: run the pump, warn the launch about the false lamp, then open the gate.',
    radio: 'She understood the wiring better than I did. I should have listened.',
  },
  {
    id: 'tunnel_chalk', world: [157, 138], nearSite: 'tunnel', minChapter: 3, optional: true,
    name: 'Chalk on the service conduit', category: 'FIELD NOTE',
    purpose: 'Make Iris’s route legible on the ground and direct exploration back to the pump house.',
    body: '<p>A chalk arrow on the conduit points from the tunnel path toward the pump house. Beneath it Iris wrote, <em>Backup feed here; two lamps if restored.</em> Rain has blurred the last word, but not the warning.</p>',
    journal: 'Iris marked the backup route before she was trapped and warned that restoring it would light both rear lamps.',
    radio: 'She left a path for you. I did not know she had mapped so much.',
  },
  {
    id: 'tunnel_water_mark', world: [159, 152], nearSite: 'tunnel', minChapter: 4, optional: true,
    name: 'Rising-water mark', category: 'OBSERVATION',
    purpose: 'Convey immediate physical stakes during the last chapter without imposing a real-time failure timer.',
    body: '<p>Fresh silt has settled above the old flood line on the hatch frame. Water is still entering the service tunnel. Iris taps twice, pauses, then taps again. She is conserving breath and waiting for the pump.</p>',
    journal: 'The tunnel is flooding above its former high-water mark. Iris is still responding, but the pump cannot wait.',
    radio: 'Mara, please start the pump. We can argue about my part when she is outside.',
  },
];

export const EPILOGUE = '<p>At the reopened inquiry, Mara speaks before the operator does. She shows the mechanical strip, the altered export, and photographs taken from two points on the island.</p><p>She reads the captain’s statement aloud. Then she reads the note she wrote across it seventeen years ago: <em>Uncorroborated.</em></p><p>“I signed the finding,” she says. “I was wrong.”</p><p>Outside the hearing room, the captain’s family has waited through seventeen years of certainty. The corrected record cannot give that time back. It can finally say what happened.</p>';
